# Generated by Django 5.0.3 on 2024-04-05 07:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0002_alter_inventory_owned_by_delete_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Inventory.ingredient')),
            ],
        ),
        migrations.AlterField(
            model_name='inventory',
            name='ingredients',
            field=models.ManyToManyField(to='Inventory.inventoryitem'),
        ),
    ]
