# Generated by Django 5.0.3 on 2024-04-07 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0003_inventoryitem_alter_inventory_ingredients'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitem',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='unit',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='ingredients',
            field=models.ManyToManyField(blank=True, default=[], to='Inventory.inventoryitem'),
        ),
    ]
