# Generated by Django 5.0.3 on 2024-03-18 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('recipe_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('image_url', models.URLField()),
                ('publisher', models.CharField(max_length=255)),
                ('source_url', models.URLField()),
                ('cooking_time', models.IntegerField()),
                ('ingredients', models.TextField()),
            ],
        ),
    ]
